# Generated by Django 2.2.2 on 2019-06-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/users/%Y/%m/%d')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('books_received', models.PositiveSmallIntegerField()),
                ('books_donated', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
