# Generated by Django 2.2.2 on 2019-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='bookId',
            field=models.ManyToManyField(related_name='user_books', to='books.Book'),
        ),
    ]
