# Generated by Django 2.2.2 on 2019-07-01 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('edition', models.DecimalField(decimal_places=2, max_digits=3)),
                ('publisher', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ManyToManyField(to='authors.Author')),
                ('category', models.ManyToManyField(related_name='books', to='books.Category')),
            ],
        ),
    ]
